import type { Locale, ProjectStatus } from "./portfolio";

const dictionaries = {
  en: {
    nav: { services: "Services", work: "Work", process: "Process", contact: "Contact", menu: "Open menu", start: "Start a project" },
    hero: { eyebrow: "Independent systems studio · Fathallah Haj", primary: "See selected work", secondary: "Tell me what you need", live: "Live product", private: "Private system", public: "Public build", signal: "Built across product, AI, and infrastructure" },
    proof: ["Trilingual products", "Production-facing systems", "Public infrastructure code", "AI with human control"],
    paths: { eyebrow: "Two ways I can help", title: "One engineer across the product and platform boundary.", businessTitle: "For regional businesses", businessText: "Turn a strong service or catalog into a multilingual product, then automate the work behind it.", startupTitle: "For startups & product teams", startupText: "Ship an MVP, add practical AI, or make the platform easier to deploy and operate." },
    services: { eyebrow: "Services", title: "Build the outcome, not just the interface.", summary: "Each engagement is scoped around a real operating need and delivered with the infrastructure required to keep it useful." },
    work: { eyebrow: "Selected work", title: "Products people can visit. Systems engineers can inspect.", summary: "Real product surfaces, public repositories, and explicit evidence boundaries. No invented metrics or customer claims.", caseStudy: "Explore the system", liveWork: "More live product work", liveSummary: "Focused builds for regional audiences, commerce, communities, and operations." },
    proofSection: { eyebrow: "Technical proof", title: "The visible product is backed by operational depth.", summary: "I work across delivery, infrastructure, observability, data, and AI boundaries so the finished system can actually run.", groups: [{ title: "Product systems", text: "Next.js, React, Flutter, payments, authentication, admin workflows, PostgreSQL" }, { title: "Platform & delivery", text: "Kubernetes, Terraform, Ansible, ArgoCD, Helm, GitHub Actions, Jenkins" }, { title: "Reliability", text: "Prometheus, Grafana, Loki, ELK, queues, WebSockets, runbooks, incident response" }, { title: "AI automation", text: "Tool calling, grounded context, evaluations, workflow gates, human takeover" }] },
    lab: { eyebrow: "In development", title: "FocusQuest", action: "Product lab" },
    process: { eyebrow: "Working model", title: "A direct path from unclear problem to operating system.", steps: [{ title: "Frame", text: "Map the customer journey, business rules, risks, and evidence of success." }, { title: "Shape", text: "Choose the smallest architecture that can deliver the whole outcome." }, { title: "Build", text: "Ship in visible slices with tests, observability, and clear review points." }, { title: "Operate", text: "Deploy, document, measure, and make the handoff usable." }] },
    contact: { eyebrow: "Project inquiry", title: "Tell me what needs to work better.", summary: "Share the current situation, the outcome you need, and any constraints. I’ll respond with concrete next questions.", direct: "Prefer a direct channel?", privacy: "Your details are sent only to Fathallah for this project inquiry." },
    form: { name: "Name", reply: "Email or WhatsApp", company: "Company (optional)", category: "What do you need?", message: "Project context", product: "Launch a product", automation: "AI automation", reliability: "Platform reliability", unsure: "Not sure yet", placeholder: "What are you trying to launch, automate, or improve?", submit: "Send project brief", sending: "Sending…", success: "Brief sent. I’ll reply directly.", failed: "Delivery failed. Please use WhatsApp or email below.", invalid: "Check the highlighted fields and try again." },
    case: { back: "All work", problem: "Problem", audience: "Built for", role: "My role", capabilities: "What shipped", architecture: "System shape", evidence: "Evidence", stack: "Tools & interfaces", next: "Next honest step", contact: "Discuss a similar system", status: "Status", privateVisual: "Private system architecture", privateNote: "The source and customer data stay private. This view shows approved, anonymized system evidence." },
    footer: { line: "Independent product, AI, and DevOps engineering.", top: "Back to top" },
  },
  ar: {
    nav: { services: "الخدمات", work: "الأعمال", process: "المنهج", contact: "تواصل", menu: "فتح القائمة", start: "ابدأ مشروعاً" },
    hero: { eyebrow: "استوديو أنظمة مستقل · فتحلله حاج", primary: "شاهد الأعمال", secondary: "أخبرني بما تحتاج", live: "منتج مباشر", private: "نظام خاص", public: "بناء عام", signal: "خبرة تجمع المنتج والذكاء الاصطناعي والبنية التحتية" },
    proof: ["منتجات بثلاث لغات", "أنظمة موجهة للإنتاج", "شيفرة بنية تحتية عامة", "ذكاء اصطناعي بتحكم بشري"],
    paths: { eyebrow: "طريقتان للمساعدة", title: "مهندس واحد يصل المنتج بالمنصة.", businessTitle: "للأعمال الإقليمية", businessText: "حوّل خدمتك أو كتالوجك إلى منتج متعدد اللغات، ثم أتمت العمل الذي خلفه.", startupTitle: "للشركات الناشئة وفرق المنتجات", startupText: "أطلق MVP، أضف ذكاءً اصطناعياً عملياً، أو اجعل المنصة أسهل في النشر والتشغيل." },
    services: { eyebrow: "الخدمات", title: "نبني النتيجة، لا الواجهة فقط.", summary: "كل تعاون يبدأ من حاجة تشغيلية حقيقية ويشمل البنية اللازمة ليبقى النظام مفيداً." },
    work: { eyebrow: "أعمال مختارة", title: "منتجات يمكن للناس زيارتها، وأنظمة يمكن للمهندسين فحصها.", summary: "واجهات منتجات حقيقية، ومستودعات عامة، وحدود واضحة للأدلة. بلا أرقام أو ادعاءات مختلقة.", caseStudy: "استكشف النظام", liveWork: "المزيد من المنتجات المباشرة", liveSummary: "منتجات مصممة للجمهور الإقليمي والتجارة والمجتمعات والتشغيل." },
    proofSection: { eyebrow: "دليل تقني", title: "خلف المنتج الظاهر عمق تشغيلي.", summary: "أعمل عبر التسليم والبنية والمراقبة والبيانات والذكاء الاصطناعي ليعمل النظام فعلياً.", groups: [{ title: "أنظمة المنتجات", text: "Next.js، React، Flutter، الدفع، تسجيل الدخول، الإدارة، PostgreSQL" }, { title: "المنصة والتسليم", text: "Kubernetes، Terraform، Ansible، ArgoCD، Helm، GitHub Actions، Jenkins" }, { title: "الموثوقية", text: "Prometheus، Grafana، Loki، ELK، الطوابير، WebSockets، أدلة التشغيل، الاستجابة للحوادث" }, { title: "أتمتة AI", text: "استخدام الأدوات، سياق موثوق، تقييمات، بوابات سير العمل، تدخل بشري" }] },
    lab: { eyebrow: "قيد التطوير", title: "FocusQuest", action: "مختبر المنتج" },
    process: { eyebrow: "منهج العمل", title: "مسار مباشر من مشكلة غير واضحة إلى نظام عامل.", steps: [{ title: "تحديد", text: "نرسم رحلة العميل وقواعد العمل والمخاطر ودليل النجاح." }, { title: "تشكيل", text: "نختار أصغر هندسة قادرة على تقديم النتيجة كاملة." }, { title: "بناء", text: "نطلق أجزاء مرئية مع اختبارات ومراقبة ونقاط مراجعة." }, { title: "تشغيل", text: "ننشر ونوثّق ونقيس ونجعل التسليم قابلاً للاستخدام." }] },
    contact: { eyebrow: "استفسار مشروع", title: "أخبرني ما الذي يجب أن يعمل بشكل أفضل.", summary: "شارك الوضع الحالي والنتيجة المطلوبة والقيود. سأرد بأسئلة عملية للخطوة التالية.", direct: "تفضّل قناة مباشرة؟", privacy: "تُرسل بياناتك إلى فتحلله فقط لمناقشة هذا المشروع." },
    form: { name: "الاسم", reply: "البريد أو واتساب", company: "الشركة (اختياري)", category: "ماذا تحتاج؟", message: "سياق المشروع", product: "إطلاق منتج", automation: "أتمتة بالذكاء الاصطناعي", reliability: "موثوقية المنصة", unsure: "لست متأكداً بعد", placeholder: "ما الذي تريد إطلاقه أو أتمتته أو تحسينه؟", submit: "إرسال ملخص المشروع", sending: "جارٍ الإرسال…", success: "تم الإرسال. سأرد عليك مباشرة.", failed: "تعذر الإرسال. استخدم واتساب أو البريد أدناه.", invalid: "راجع الحقول وحاول مرة أخرى." },
    case: { back: "كل الأعمال", problem: "المشكلة", audience: "مبني من أجل", role: "دوري", capabilities: "ما تم بناؤه", architecture: "شكل النظام", evidence: "الأدلة", stack: "الأدوات والواجهات", next: "الخطوة الصادقة التالية", contact: "ناقش نظاماً مشابهاً", status: "الحالة", privateVisual: "هندسة نظام خاص", privateNote: "تبقى الشيفرة وبيانات العملاء خاصة. يعرض هذا القسم أدلة نظام معتمدة ومجهّلة." },
    footer: { line: "هندسة منتجات وذكاء اصطناعي وDevOps بشكل مستقل.", top: "إلى الأعلى" },
  },
  he: {
    nav: { services: "שירותים", work: "עבודות", process: "תהליך", contact: "יצירת קשר", menu: "פתיחת תפריט", start: "התחלת פרויקט" },
    hero: { eyebrow: "סטודיו עצמאי למערכות · פתאללה חאג'", primary: "לעבודות נבחרות", secondary: "ספרו לי מה נדרש", live: "מוצר חי", private: "מערכת פרטית", public: "בנייה ציבורית", signal: "נבנה לאורך מוצר, AI ותשתיות" },
    proof: ["מוצרים בשלוש שפות", "מערכות מוכוונות ייצור", "קוד תשתית ציבורי", "AI עם שליטה אנושית"],
    paths: { eyebrow: "שתי דרכים לעזור", title: "מהנדס אחד בין המוצר לפלטפורמה.", businessTitle: "לעסקים אזוריים", businessText: "הפכו שירות או קטלוג למוצר רב-לשוני, ואז בצעו אוטומציה לעבודה שמאחוריו.", startupTitle: "לסטארטאפים וצוותי מוצר", startupText: "השיקו MVP, הוסיפו AI מעשי או הפכו את הפלטפורמה לקלה יותר לפריסה ולתפעול." },
    services: { eyebrow: "שירותים", title: "בונים את התוצאה, לא רק את הממשק.", summary: "כל התקשרות מוגדרת סביב צורך תפעולי אמיתי וכוללת את התשתית שתשמור על המערכת שימושית." },
    work: { eyebrow: "עבודות נבחרות", title: "מוצרים שאפשר לבקר בהם. מערכות שמהנדסים יכולים לבדוק.", summary: "מסכי מוצר אמיתיים, מאגרים ציבוריים וגבולות ראיות ברורים. ללא מדדים או טענות מומצאים.", caseStudy: "לחקירת המערכת", liveWork: "עוד מוצרים חיים", liveSummary: "בניות ממוקדות לקהלים אזוריים, מסחר, קהילות ותפעול." },
    proofSection: { eyebrow: "הוכחה טכנית", title: "מאחורי המוצר הגלוי יש עומק תפעולי.", summary: "אני עובד לאורך מסירה, תשתיות, ניטור, נתונים ו-AI כדי שהמערכת המוגמרת באמת תפעל.", groups: [{ title: "מערכות מוצר", text: "Next.js, React, Flutter, תשלומים, אימות, ניהול, PostgreSQL" }, { title: "פלטפורמה ומסירה", text: "Kubernetes, Terraform, Ansible, ArgoCD, Helm, GitHub Actions, Jenkins" }, { title: "אמינות", text: "Prometheus, Grafana, Loki, ELK, תורים, WebSockets, ספרי הפעלה ותגובה לתקריות" }, { title: "אוטומציית AI", text: "שימוש בכלים, הקשר מהימן, הערכות, שערי תהליך ומעבר לאדם" }] },
    lab: { eyebrow: "בפיתוח", title: "FocusQuest", action: "מעבדת מוצר" },
    process: { eyebrow: "מודל עבודה", title: "מסלול ישיר מבעיה לא ברורה למערכת מתפקדת.", steps: [{ title: "מסגור", text: "ממפים את מסע הלקוח, הכללים, הסיכונים והוכחת ההצלחה." }, { title: "עיצוב", text: "בוחרים את הארכיטקטורה הקטנה ביותר שמספקת את התוצאה המלאה." }, { title: "בנייה", text: "משחררים חלקים נראים עם בדיקות, ניטור ונקודות ביקורת." }, { title: "תפעול", text: "פורסים, מתעדים, מודדים והופכים את המסירה לשימושית." }] },
    contact: { eyebrow: "פניית פרויקט", title: "ספרו לי מה צריך לעבוד טוב יותר.", summary: "שתפו את המצב הנוכחי, התוצאה הנדרשת והמגבלות. אחזור עם שאלות קונקרטיות להמשך.", direct: "מעדיפים ערוץ ישיר?", privacy: "הפרטים נשלחים רק לפתאללה לצורך פניית הפרויקט." },
    form: { name: "שם", reply: "דוא״ל או WhatsApp", company: "חברה (אופציונלי)", category: "מה נדרש?", message: "הקשר הפרויקט", product: "השקת מוצר", automation: "אוטומציית AI", reliability: "אמינות פלטפורמה", unsure: "עדיין לא בטוח", placeholder: "מה תרצו להשיק, להפוך לאוטומטי או לשפר?", submit: "שליחת תקציר פרויקט", sending: "שולח…", success: "התקציר נשלח. אחזור אליכם ישירות.", failed: "השליחה נכשלה. השתמשו ב-WhatsApp או בדוא״ל למטה.", invalid: "בדקו את השדות ונסו שוב." },
    case: { back: "כל העבודות", problem: "הבעיה", audience: "נבנה עבור", role: "התפקיד שלי", capabilities: "מה נבנה", architecture: "מבנה המערכת", evidence: "ראיות", stack: "כלים וממשקים", next: "הצעד הכנה הבא", contact: "שיחה על מערכת דומה", status: "סטטוס", privateVisual: "ארכיטקטורת מערכת פרטית", privateNote: "הקוד ונתוני הלקוחות נשארים פרטיים. כאן מוצגות ראיות מערכת מאושרות ואנונימיות." },
    footer: { line: "הנדסת מוצר, AI ו-DevOps באופן עצמאי.", top: "חזרה למעלה" },
  },
} as const;

export const getDictionary = (locale: Locale) => dictionaries[locale];

export const statusLabels: Record<ProjectStatus, Record<Locale, string>> = {
  "live-product": { en: "Live product work", ar: "منتج مباشر", he: "מוצר חי" },
  "public-build": { en: "Public engineering build", ar: "بناء هندسي عام", he: "בנייה הנדסית ציבורית" },
  "private-build": { en: "Private system", ar: "نظام خاص", he: "מערכת פרטית" },
  "in-development": { en: "In development", ar: "قيد التطوير", he: "בפיתוח" },
};
